services:
  mysqldb:
    image: mysql:8.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql


  spring-app:
    build:
      context: .  # raiz del proyecto
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mysqldb
    environment:
      # mismas credenciales
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}?useSSL=false"
      SPRING_DATASOURCE_USERNAME: "${MYSQLDB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
    ports:
      - "8080:8080"


  python-api:
    build:
      context: ./api-flask
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: libreria
    ports:
      - "5000:5000"
    volumes:
      - ./api-flask/files:/app/files
    depends_on:
      - mysqldb

volumes:
  db:
